server:
  port: 8080

spring:
  application:
    name: main-service

  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        ip: ${NACOS_DISCOVERY_IP:127.0.0.1}
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        file-extension: yaml
