CREATE TABLE `course` (
                          `id` bigint unsigned NOT NULL COMMENT '课程ID，建议使用 MyBatis-Plus ASSIGN_ID 雪花ID',
                          `categoryName` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '课程分类名称，例如：JavaSE、JavaEE、Redis、MySQL',
                          `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '课程标题',
                          `subtitle` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '课程副标题/卖点文案',
                          `coverUrl` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '课程封面图URL',
                          `teacherName` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '讲师名称，轻量版可先冗余保存',
                          `summary` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '课程摘要，用于列表和详情页简短介绍',
                          `detail` text COLLATE utf8mb4_unicode_ci COMMENT '课程详情，可存富文本HTML或Markdown',
                          `price` int unsigned NOT NULL DEFAULT '0' COMMENT '课程售价，单位：分',
                          `episodeCount` int unsigned NOT NULL DEFAULT '0' COMMENT '课程章节数，由章节表同步维护',
                          `buyCount` int unsigned NOT NULL DEFAULT '0' COMMENT '购买人数/销量',
                          `sort` int NOT NULL DEFAULT '0' COMMENT '排序值，越大越靠前',
                          `status` tinyint NOT NULL DEFAULT '0' COMMENT '课程状态：0草稿 1上架 2下架',
                          `chargeType` tinyint NOT NULL DEFAULT '1' COMMENT '收费类型：0免费 1付费 2VIP免费',
                          `createdUser` bigint unsigned NOT NULL DEFAULT '0' COMMENT '创建人ID',
                          `updatedUser` bigint unsigned NOT NULL DEFAULT '0' COMMENT '更新人ID',
                          `createTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                          `updateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                          `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除 1已删除',
                          PRIMARY KEY (`id`),
                          KEY `idx_client_list` (`deleted`,`status`,`categoryName`,`sort`),
                          KEY `idx_admin_list` (`deleted`,`status`,`createTime`),
                          KEY `idx_title` (`title`),
                          KEY `idx_createTime` (`createTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课程表';