CREATE TABLE `course_order` (
                                `id` bigint unsigned NOT NULL COMMENT '订单ID，雪花ID',
                                `orderNo` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '订单号，对外展示和支付使用',
                                `userId` bigint unsigned NOT NULL COMMENT '用户ID',
                                `courseId` bigint unsigned NOT NULL COMMENT '课程ID',
                                `userCouponId` bigint unsigned DEFAULT NULL COMMENT '使用的用户优惠券ID',
                                `couponName` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '优惠券名称快照',
                                `discountAmount` int unsigned NOT NULL DEFAULT '0' COMMENT '优惠金额，单位：分',
                                `courseTitle` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '课程标题快照',
                                `coverUrl` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '课程封面快照',
                                `coursePrice` int unsigned NOT NULL DEFAULT '0' COMMENT '课程原价，单位分',
                                `payAmount` int unsigned NOT NULL DEFAULT '0' COMMENT '实付金额，单位分',
                                `status` tinyint NOT NULL DEFAULT '0' COMMENT '订单状态：0待支付 1已支付 2已取消 3已退款 4已关闭',
                                `payType` tinyint NOT NULL DEFAULT '0' COMMENT '支付方式：0未支付 1微信 2支付宝 3模拟支付',
                                `thirdTradeNo` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '第三方支付流水号',
                                `expireTime` datetime DEFAULT NULL COMMENT '订单过期时间',
                                `payTime` datetime DEFAULT NULL COMMENT '支付时间',
                                `cancelTime` datetime DEFAULT NULL COMMENT '取消时间',
                                `refundTime` datetime DEFAULT NULL COMMENT '退款时间',
                                `createdUser` bigint unsigned NOT NULL DEFAULT '0' COMMENT '创建人ID',
                                `updatedUser` bigint unsigned NOT NULL DEFAULT '0' COMMENT '更新人ID',
                                `createTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                `updateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除 1已删除',
                                PRIMARY KEY (`id`),
                                UNIQUE KEY `uk_orderNo` (`orderNo`),
                                KEY `idx_user_list` (`userId`,`deleted`,`status`,`createTime`),
                                KEY `idx_admin_list` (`deleted`,`status`,`createTime`),
                                KEY `idx_course_user` (`courseId`,`userId`,`deleted`),
                                KEY `idx_expire_scan` (`status`,`expireTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课程订单表';