CREATE TABLE `user_coupon` (
                               `id` bigint unsigned NOT NULL COMMENT '用户优惠券ID，雪花ID',
                               `couponTemplateId` bigint unsigned NOT NULL COMMENT '优惠券模板ID',
                               `userId` bigint unsigned NOT NULL COMMENT '领取用户ID',
                               `couponName` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '优惠券名称快照',
                               `thresholdAmount` int unsigned NOT NULL DEFAULT '0' COMMENT '使用门槛金额快照，单位：分',
                               `discountAmount` int unsigned NOT NULL COMMENT '优惠金额快照，单位：分',
                               `status` tinyint NOT NULL DEFAULT '0' COMMENT '使用状态：0未使用 1已锁定 2已使用 3已过期',
                               `orderId` bigint unsigned DEFAULT NULL COMMENT '锁定或使用该优惠券的订单ID',
                               `lockTime` datetime DEFAULT NULL COMMENT '优惠券锁定时间',
                               `lockExpireTime` datetime DEFAULT NULL COMMENT '锁定过期时间',
                               `useTime` datetime DEFAULT NULL COMMENT '实际使用时间',
                               `validStartTime` datetime NOT NULL COMMENT '有效期开始时间',
                               `validEndTime` datetime NOT NULL COMMENT '有效期结束时间',
                               `createdUser` bigint unsigned NOT NULL DEFAULT '0' COMMENT '创建人ID',
                               `updatedUser` bigint unsigned NOT NULL DEFAULT '0' COMMENT '更新人ID',
                               `createTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '领取时间',
                               `updateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                               `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除 1已删除',
                               PRIMARY KEY (`id`),
                               UNIQUE KEY `uk_user_coupon_template` (`userId`,`couponTemplateId`),
                               KEY `idx_user_status_create` (`userId`,`deleted`,`status`,`createTime`),
                               KEY `idx_user_coupon_list` (`userId`,`deleted`,`status`,`validEndTime`),
                               KEY `idx_orderId` (`orderId`),
                               KEY `idx_locked_expire` (`status`,`lockExpireTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;