CREATE TABLE `payment_order` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT '支付单ID，雪花ID',
    `paymentNo` VARCHAR ( 64 ) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '支付单号，由支付服务生成并提交给第三方支付平台',
    `bizType` TINYINT NOT NULL COMMENT '业务类型：1课程订单,暂时只有课程订单',
    `bizOrderId` BIGINT UNSIGNED NOT NULL COMMENT '业务订单ID，例如course_order.id',
    `bizOrderNo` VARCHAR ( 64 ) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务订单号快照，例如course_order.orderNo',
    `userId` BIGINT UNSIGNED NOT NULL COMMENT '支付用户ID',
    `subject` VARCHAR ( 200 ) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '支付标题，例如：购买Java课程',
    `payAmount` INT UNSIGNED NOT NULL COMMENT '支付金额，单位：分',
    `currency` VARCHAR ( 10 ) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CNY' COMMENT '货币类型',
    `payChannel` TINYINT NOT NULL COMMENT '支付渠道：1微信 2支付宝 3模拟支付',
    `status` TINYINT NOT NULL DEFAULT '0' COMMENT '支付状态：0待支付 1支付成功 2已关闭 3支付失败',
    `thirdTradeNo` VARCHAR ( 100 ) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '第三方支付流水号',
    `codeUrl` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '微信Native支付二维码内容',
    `failureReason` VARCHAR ( 255 ) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '支付失败原因',
    `expireTime` DATETIME NOT NULL COMMENT '支付单过期时间',
    `payTime` DATETIME DEFAULT NULL COMMENT '支付成功时间',
    `closeTime` DATETIME DEFAULT NULL COMMENT '支付单关闭时间',
    `createdUser` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建人ID',
    `updatedUser` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新人ID',
    `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY ( `id` ),
    UNIQUE KEY `uk_paymentNo` ( `paymentNo` ),
    UNIQUE KEY `uk_biz_order` ( `bizType`, `bizOrderId` ),
    UNIQUE KEY `uk_channel_thirdTradeNo` ( `payChannel`, `thirdTradeNo` ),
    KEY `idx_user_list` ( `userId`, `status`, `createTime` ),
    KEY `idx_expire_scan` ( `status`, `expireTime` )
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '支付订单表';