CREATE TABLE `mq_dead_message` (
                                   `id` bigint unsigned NOT NULL COMMENT '死信消息ID，雪花ID',
                                   `bizType` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '业务类型，例如：PAYMENT_SUCCESS',
                                   `bizId` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '业务ID，例如：paymentNo',
                                   `sourceQueue` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原始业务队列名称',
                                   `sourceExchange` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原始业务交换机名称',
                                   `sourceRoutingKey` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原始业务路由键',
                                   `deadQueue` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '死信队列名称',
                                   `deadExchange` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '死信交换机名称',
                                   `deadRoutingKey` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '死信路由键',
                                   `messageBody` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息体JSON',
                                   `headers` text COLLATE utf8mb4_unicode_ci COMMENT '消息头JSON',
                                   `deadReason` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '进入死信原因',
                                   `lastError` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '最后一次处理错误',
                                   `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0待处理 1已重投 2忽略 3重投失败',
                                   `retryCount` int unsigned NOT NULL DEFAULT '0' COMMENT '人工重投次数',
                                   `lastRetryTime` datetime DEFAULT NULL COMMENT '最后一次人工重投时间',
                                   `createdUser` bigint unsigned NOT NULL DEFAULT '0' COMMENT '创建人ID',
                                   `updatedUser` bigint unsigned NOT NULL DEFAULT '0' COMMENT '更新人ID',
                                   `createTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                   `updateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                   `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除 1已删除',
                                   PRIMARY KEY (`id`),
                                   KEY `idx_status_createTime` (`deleted`,`status`,`createTime`),
                                   KEY `idx_biz` (`bizType`,`bizId`),
                                   KEY `idx_source_queue` (`sourceQueue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ死信消息表';