CREATE TABLE `payment_refund_order` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT '退款单ID，雪花ID',
    `refundNo` VARCHAR ( 64 ) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '退款单号，由支付服务生成并提交给第三方支付平台',
    `paymentNo` VARCHAR ( 64 ) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原支付单号',
    `bizType` TINYINT NOT NULL COMMENT '业务类型：1课程订单',
    `bizOrderId` BIGINT UNSIGNED NOT NULL COMMENT '业务订单ID，例如course_order.id',
    `bizOrderNo` VARCHAR ( 64 ) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务订单号快照，例如course_order.orderNo',
    `userId` BIGINT UNSIGNED NOT NULL COMMENT '退款用户ID',
    `payAmount` INT UNSIGNED NOT NULL COMMENT '原支付金额，单位：分',
    `refundAmount` INT UNSIGNED NOT NULL COMMENT '退款金额，单位：分',
    `currency` VARCHAR ( 10 ) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CNY' COMMENT '货币类型',
    `payChannel` TINYINT NOT NULL COMMENT '支付渠道：1微信 2支付宝 3模拟支付',
    `status` TINYINT NOT NULL DEFAULT '0' COMMENT '退款状态：0待退款 1退款中 2退款成功 3退款失败 4已关闭',
    `thirdTradeNo` VARCHAR ( 100 ) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '原第三方支付流水号',
    `thirdRefundNo` VARCHAR ( 100 ) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '第三方退款流水号',
    `refundReason` VARCHAR ( 255 ) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '退款原因',
    `failureReason` VARCHAR ( 500 ) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '退款失败原因',
    `applyTime` DATETIME NOT NULL COMMENT '退款申请时间',
    `refundTime` DATETIME DEFAULT NULL COMMENT '退款成功时间',
    `closeTime` DATETIME DEFAULT NULL COMMENT '退款关闭时间',
    `createdUser` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建人ID',
    `updatedUser` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新人ID',
    `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT '0' COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY ( `id` ),
    UNIQUE KEY `uk_refundNo` ( `refundNo` ),
    UNIQUE KEY `uk_biz_order` ( `bizType`, `bizOrderId` ),
    KEY `idx_paymentNo` ( `paymentNo` ),
    KEY `idx_user_list` ( `userId`, `status`, `createTime` ),
    KEY `idx_channel_thirdRefundNo` ( `payChannel`, `thirdRefundNo` ),
    KEY `idx_createTime` ( `createTime` )
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '支付退款订单表';